#! /bin/sh


xset +fp /home/mjh/.local/share/fonts &
xset fp rehash &
xinput --set-prop 13 "libinput Natural Scrolling Enabled" 1 &
xinput --set-prop 13 "libinput Tapping Enabled" 1 &

#xrandr -s 1920x1080
feh --bg-fill --randomize ~/Pictures/wallpapers/dracula/ &
compton &
sxhkd &
polybar example &
dunst &
clipmenud &
xautolock -time 5 -locker 'betterlockscreen -l dim' &

mopidy &
feh --bg-fill ~/Pictures/auuBhVW.png

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp state=floating follow=on

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
