#! /bin/sh

#xrandr -s 1920x1080
xset +fp /home/matthew/.local/share/fonts
xset fp rehash
compton &
sxhkd &
polybar example &
dunst &

mopidy &
feh --bg-fill ~/Pictures/auuBhVW.png

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp state=floating follow=on
