theme = "ayu_dark"

[editor]
line-number = "relative"
scrolloff = 0
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-type"]
separator = "│"

[keys.normal]
"," = "collapse_selection"
";" = "keep_primary_selection"
A-J = "join_selections"
A-K = "remove_selections"
A-k = "keep_selections"
B = "extend_prev_word_start"
E = "extend_next_word_end"
H = "extend_char_left"
J = "extend_line_down"
K = "extend_line_up"
L = "extend_char_right"
N = "extend_search_next"
W = "extend_next_word_start"
X = "extend_line_below"

[keys.normal.space]
"," = "buffer_picker"
space = "file_picker"

[keys.normal.space.c]
D = "workspace_diagnostics_picker"
R = "rename_symbol"
S = "workspace_symbol_picker"
a = "code_action"
d = "diagnostics_picker"
s = "symbol_picker"
