theme = "ayu_dark"

[editor]
true-color = true
line-number = "relative"
scrolloff = 0

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-type"]
separator = "│"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"H" = "extend_char_left"
"L" = "extend_char_right"
"J" = "extend_line_down"
"K" = "extend_line_up"

"W" = "extend_next_word_start"
"B" = "extend_prev_word_start"
"X" = "extend_line_below"

";" = "keep_primary_selection"
"," = "collapse_selection"

"A-J" = "join_selections"

"A-k" = "keep_selections"
"A-K" = "remove_selections"

"N" = "extend_search_next"

[keys.normal.space]
"space" = "file_picker"
"," = "buffer_picker"

[keys.normal.space.c]
"s" = "symbol_picker"
"S" = "workspace_symbol_picker"
"d" = "diagnostics_picker"
"D" = "workspace_diagnostics_picker"
"R" = "rename_symbol"
"a" = "code_action"